### ISSUE TITLE
TIER III frontend: Create delete button on single item

### ISSUE THREAD

**Issue by berat-552** [swe21-inventory-app-group-B/inventory-app#11]
- On each item, there should be a button which deletes that item from the database
- Create an `onClick={() => deleteItem(id)}` handler function which takes an id as a parameter
- function should use that id to delete the item.
- It should use it's ID to make a request to `DELETE http://localhost:3000/api/items/:id`
- After delete function is performed, fetch the latest data to show that the delete was successful.

This issue cannot be closed unless #12 is completed.

**Comment by berat-552** [comment]
this is now able to be started because #12 is completed @pookieboot

**Comment by pookieboot** [comment]
I have started but I will continue this when I'm back at home. Will be done at 1800 :)

**Comment by pookieboot** [comment]
![cute](https://github.com/user-attachments/assets/10f1e90f-5faf-45e1-8e7b-674f9cd77230)

**Comment by pookieboot** [comment]
didnt get it done yesterday will finish now :(

**Comment by berat-552** [comment]
no problem
