### ISSUE TITLE
BONUS: make the frontend look clean and nice

### ISSUE THREAD

**Issue by berat-552** [swe21-inventory-app-group-B/inventory-app#22]
- feel free to add your own adjustments to make the UI look clean, as of now it's not looking great.. 

- again this is optional so do not feel pressured by it @pookieboot i can also pitch in some help with the styling

**Comment by pookieboot** [comment]
working on this rn, i am slow so itll be done by 7pm max (as long as i dont puke)

**Comment by berat-552** [comment]
yeh no problem get well soon

**Comment by pookieboot** [comment]
Ye so its 00:18 woke up and remembered i had work to do. if its not up to standards i apologise i was sleepy hehehhhehehehe

**Comment by berat-552** [comment]
@pookieboot https://www.instagram.com/reel/DCXakIcRqoA/?igsh=MWJsZzFpaDFtaXphZA==

Real 😭

**Comment by pookieboot** [comment]
AHSUUSADUEWDWI LOOOOOOL 😭😭

**Comment by pookieboot** [comment]
damn didnt mean that LMAOOO

**Comment by pookieboot** [comment]
ALSO REELS ON GITHUB LMFAO

**Comment by berat-552** [comment]
Fr this has never been done before I think this is a first to send reeks on github 😭😭

**Comment by pookieboot** [comment]
LITERALLY HAHAHAHA. very smart tho lol

**Comment by berat-552** [comment]
https://github.com/user-attachments/assets/8c537b8e-b2b4-451e-b1cd-176494095b9a

**Comment by pookieboot** [comment]
HAHAHAAH YES 100% @berat-552

**Comment by berat-552** [comment]
😭😭😭 fr

**Comment by berat-552** [comment]
![Screenshot_20241201_182550_Instagram.jpg](https://github.com/user-attachments/assets/886c34cc-157e-44c7-aeb8-fb1098a3c215)

**Comment by berat-552** [comment]
![Screenshot_20241122_095548_Instagram.jpg](https://github.com/user-attachments/assets/437a4a55-d182-4afd-a513-a13e7c893bb7)

**Comment by berat-552** [comment]
https://www.instagram.com/reel/DCrdYTOoX7H/?igsh=MTM2M2FnZXVqN3oxcQ==

Now this is an elite pickle shop fr
